### ISSUE TITLE
Error with TCP/IP

### ISSUE THREAD

**Issue by darkat** [javierdelapuente/reeprotocol#4]
When i try connect with tcpip_cliente.py, script send init bytes, i get a error:

> 
> INFO:root:->10:49:01:00:4a:16
> Traceback (most recent call last):
>   File ".\tcpip_cliente.py", line 76, in <module>
>     run_example(ip, port, der, dir_pm, clave_pm)
>   File ".\tcpip_cliente.py", line 23, in run_example
>     link_layer.link_state_request()
>   File "D:\...\gitproyect\reeprotocol\examples\..\reeprotocol\protocol.py", line 116, in link_state_request
>     resp = self.get_frame()
>   File "D:\...\gitproyect\reeprotocol\examples\..\reeprotocol\protocol.py", line 107, in get_frame
>     bt = self.physical_layer.get_byte(timeout)
>   File "D:\...\gitproyect\reeprotocol\examples\..\reeprotocol\tcpip.py", line 44, in get_byte
>     return self.queue.get(True, timeout)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python36-32\lib\queue.py", line 172, in get
>     raise Empty
> queue.Empty

With other programs, for instance ISM _"Lector de contadores"_, when i send:

> ->10-49-01-00-4A-16

I received:

> <-10-0B-01-00-0C-16

.....

**Comment by javierdelapuente** [comment]
Hi darkat,

default timeout for get_timeout is 60 seconds. Could you increase it in LinkLayer.get_frame to see if that is the problem?
